language: node_js
node_js:
  - "0.10"
branches:
    only:
        - "master"
env:
    global:
        # GH_TOKEN is the oauth token generated as described at
        # https://help.github.com/articles/creating-an-oauth-token-for-command-line-use
        #
        # curl -u 'username' -d '{"scopes":["repo"],"note":"push to <%= destinationBranch %> from travis"}' https://api.github.com/authorizations
        #
        # You have to encrypt it with travis gem
        # http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
        #
        # travis encrypt GH_TOKEN=XYXYXYXYXY
        #
        - secure: "Sea9Szq1qc54fHnvWE5gMs2Uenbb0g+Rf7bURk30TTndsWRyhbAnM3Dj1gqN3oTW3+1ZUL4Vmh9UAx55lL8YGMrql3D6Fo4WnHsOkDWJFM42CCyusApsI+8zoApbwpph1cYWkdSCmCmCAeodyMFw5v3aGFWKzgtG50OlAGD1h98="
before_install:
  - "gem install compass"
  - "npm install -g grunt-contrib-compass"
  - "npm install"
  - "npm install -g grunt-cli bower"
install:
  - "bower install"
script:
  - "grunt"